
POST http://classifica.gmasiero.it/studente HTTP/1.1
content-type: application/json

{
    "username": "6",
    "punteggio": "1",
    "sezione": "test"
}

###
GET http://classifica.gmasiero.it/admin HTTP/1.1
Authorization: Basic YWRtaW46QGRtaW4h

###
GET http://classifica.gmasiero.it/admin/studenti HTTP/1.1
Authorization: Basic YWRtaW46QGRtaW4h

###\
POST http://classifica.gmasiero.it/admin HTTP/1.1
Authorization: Basic YWRtaW46QGRtaW4h
content-type: application/json

{
    "action": "backup"
}

###
POST http://classifica.gmasiero.it/admin HTTP/1.1
Authorization: Basic YWRtaW46QGRtaW4h
content-type: application/json

{
    "action": "createStudent",
    "username": "nuovo_studente",
    "sezione": "3A",
    "punteggio": 12
}

###
POST http://classifica.gmasiero.it/admin HTTP/1.1
Authorization: Basic YWRtaW46QGRtaW4h
content-type: application/json

{
    "action": "setScore",
    "id": 1,
    "punteggio": 100
}

###
POST http://classifica.gmasiero.it/admin HTTP/1.1
Authorization: Basic YWRtaW46QGRtaW4h
content-type: application/json

{
    "action": "updateStudent",
    "id": 1,
    "username": "mario",
    "sezione": "4B",
    "punteggio": 99
}

###
POST http://classifica.gmasiero.it/admin HTTP/1.1
Authorization: Basic YWRtaW46QGRtaW4h
content-type: application/json

{
    "action": "deleteStudent",
    "id": 2
}

###
POST http://localhost:3000/admin HTTP/1.1
Authorization: Basic YWRtaW46QGRtaW4h
content-type: application/json

{
    "action": "reset"
}